### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by caseyyee** [EFForg/spot_the_surveillance#101]
@lschatzkin @Maassive @cvan 
🎉 Wohoo! Now that we've gotten the experience running smoothly with the Oculus Go using Firefox Reality Browser, I'd like to get the changes deployed and the experience featured in the Firefox Reality Content Feed.

If you could, reference any last issues you want fixed and consider a blocker before we get this project featured on the feed!

**Comment by lschatzkin** [comment]
@caseyyee Oh hey! I just sent you an email asking about next steps!

I'll mark all blockers, thanks!

@Maassive I have the changes on the dev server for your review, so we should run through that together to make sure I haven't missed anything.

**Comment by lschatzkin** [comment]
@caseyyee We will also have a Spanish version in a couple of weeks. If you don't want to wait for that to feature it, perhaps you can at least mention that it is about to be released.

**Comment by Maassive** [comment]
I'll be back in the office on Thursday to go through it.

**Comment by caseyyee** [comment]
I don't think as of yet, we have any Spanish support in Firefox Reality, so doesn't mean much for us.  We can launch this into the feed without the Spanish version maybe?  We can re-feature it later too.
