### ISSUE TITLE
Ambient audio not restarting on replay in Oculus Browser;

### ISSUE THREAD

**Issue by lschatzkin** [EFForg/spot_the_surveillance#114]
Also, no audio is loading for me on Replay in Firefox Reality.

**Comment by lschatzkin** [comment]
@caseyyee Sorry I just noticed this!

**Comment by caseyyee** [comment]
@lschatzkin did you try https://github.com/EFForg/spot_the_surveillance/pull/107  to see if this resolves the issue?

**Comment by lschatzkin** [comment]
I thought I did, but let me try again.
