### ISSUE TITLE
Screenshot of the Mozilla VR Experience

### ISSUE THREAD

**Issue by okaysoraya** [EFForg/spot_the_surveillance#125]
So we can promote it :)

**Comment by lschatzkin** [comment]
@okaysoraya Here's two versions:
![firefox-reality1](https://user-images.githubusercontent.com/852512/54956387-16f78480-4f0d-11e9-8ea2-b4b67da98dad.png)
![firefox-reality2](https://user-images.githubusercontent.com/852512/54956399-1bbc3880-4f0d-11e9-9820-daeb34381e51.png)

**Comment by lschatzkin** [comment]
...And one more:
![firefox-reality3](https://user-images.githubusercontent.com/852512/54956517-5f16a700-4f0d-11e9-9549-8f2383a5907e.png)
