### ISSUE TITLE
Sound stutters on load when using Firefox Reality on Oculus Go

### ISSUE THREAD

**Issue by caseyyee** [EFForg/spot_the_surveillance#62]
While loading the experience, the sound stutters for a good minute or so until assets are properly loaded.

**Comment by lschatzkin** [comment]
Hi Casey, thanks for finding this bug! Can you point me to where I can find info on how to properly load the assets to avoid this?

**Comment by caseyyee** [comment]
I just submitted a PR for this: https://github.com/EFForg/spot_the_surveillance/pull/70
