### ISSUE TITLE
Go: PTZ camera audio turns on and off when moving head (while cursor is still on card)

### ISSUE THREAD

**Issue by lschatzkin** [EFForg/spot_the_surveillance#68]

**Comment by caseyyee** [comment]
Looks like what is happening here is the sound level is set to 0 (mute), but continues to play. When the users gaze ends up back on the card, the sound level turned up again.

The proper behavior is probably to have the audio playback from the beginning when you look at the card?

**Comment by caseyyee** [comment]
Does this still happen since https://github.com/EFForg/spot_the_surveillance/commit/09874459b776904b5ff5902a22299b6c8f21a60e ?

**Comment by caseyyee** [comment]
Ah, so I just noticed this one. It only happens to the PTZ camera audio. I think it might be the card geometry or something.
