### ISSUE TITLE
Consider using `window.requestIdleCallback` for loading hotspot audio tracks

### ISSUE THREAD

**Issue by cvan** [EFForg/spot_the_surveillance#84]
It'd be nice to use [**`window.requestIdleCallback`**](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback) to [**load**](https://github.com/EFForg/spot_the_surveillance/pull/70/files/12de8fdd36b293ba689b825545c6eb3c3f615b03#diff-f34d5dddff844edea04f51bf4797b4a2R27) (but not yet play) the sounds, instead of loading + playing the sounds on the `mouseenter` event.

See discussion in PR #70: https://github.com/EFForg/spot_the_surveillance/pull/70#discussion_r250799393

**Comment by caseyyee** [comment]
Fixed with https://github.com/EFForg/spot_the_surveillance/pull/70/commits/155250123c3dd0eb152b08ff1504ea9967499e62
