### ISSUE TITLE
Disable "Get Started" modal when a player begins playing (finds a hotspot)

### ISSUE THREAD

**Issue by cvan** [EFForg/spot_the_surveillance#85]
As a nice UX enhancement, it could be nice to dismiss the **Get Started** modal when the player has already started playing the game and finds a hotspot.

**Comment by cvan** [comment]
@lschatzkin @caseyyee: It appears that the black background does not appear in Firefox Reality but it does in Oculus Browser. I assume this is a minor bug with the platform detection.

From running a local server with the latest `master` on Oculus Browser and Firefox Reality:

# Oculus Browser

## On page load (before pressing any button)
Audio narration begins. Notice the black background appears, drawing the user's focus to the **Get Started** modal and the **Enter VR** button at the bottom right.

![image](https://user-images.githubusercontent.com/203725/53062513-e6d44600-3475-11e9-8c59-540b596e08cf.png)

## Upon entering VR
Notice the black background still appears, drawing the user's focus to the **Get Started** modal.

![image](https://user-images.githubusercontent.com/203725/53062549-09665f00-3476-11e9-9fea-a83cd9800554.png)

# Firefox Reality

## On page load (before pressing any button)
Audio narration begins. Notice the black background _**does not**_ appear.

![image](https://user-images.githubusercontent.com/203725/53062574-1be09880-3476-11e9-8bf0-1d940f89ece5.png)

## Upon entering VR
Because the black background _**does not**_ appear (as it does in Oculus Browser), I found myself getting confused that I couldn't begin the game without gazing my eye to dismiss the **Get Started** modal.

![image](https://user-images.githubusercontent.com/203725/53062700-7da10280-3476-11e9-9c6b-581b94ed6106.png)

<hr>

@caseyyee commented in issue #79, https://github.com/EFForg/spot_the_surveillance/issues/79#issuecomment-460771667:

> The approach in #85 can work, but I think that it's good to have people understand what the premise of the experience is.
> 
> My thought was that the user has to first see and acknowledge the "Get Started" card before any of the hotspots are active, that way the user has instruction and knows what's going on before looking for hotspots. This would also prevent issue https://github.com/EFForg/spot_the_surveillance/issues/86 from happening before the user plays any of the experience.

**Comment by cvan** [comment]
Gotcha, I think I understand better. In my screenshots above, are do the screenshots for Oculus Browser show the behaviour you expect for users in standalone VR browsers?

I opened a PR to make the change that satisfies the effect I believe you are looking for: https://github.com/EFForg/spot_the_surveillance/pull/115/files

Hope that helps. Thank you.

**Comment by lschatzkin** [comment]
> Gotcha, I think I understand better. In my screenshots above, do the [screenshots above](https://github.com/EFForg/spot_the_surveillance/issues/85#issuecomment-465398460) for Oculus Browser show the behaviour you expect for users in standalone VR browsers?
> 
> I opened a PR to make the change that satisfies the effect I believe you are looking for: https://github.com/EFForg/spot_the_surveillance/pull/115/files
> 
> Hope that helps. Thank you.

Yes, we do want the black bg to appear in standalone VR browsers.

Please see my note on your pull request.
