### ISSUE TITLE
"Exit Game" modal sometimes accidentally appears upon entering VR

### ISSUE THREAD

**Issue by cvan** [EFForg/spot_the_surveillance#86]
1. Point the headset a bit downward.
2. Press the Enter VR button.
3. Notice the **Exit Game** modal appears.

This is jarring and confusing, but it does not consistently happen (it's dependent on where your head is pointed).

![eff](https://user-images.githubusercontent.com/203725/52155633-9917ab00-2638-11e9-8422-a3a88eb8b120.png)

**Comment by caseyyee** [comment]
Hmm. More than likely this is probably because your headset was pointed down at EFF logo which triggered the popup.

**Comment by cvan** [comment]
Yeah, I think so. Should the hotspots / hoverable regions be engaged only after entering VR mode (`enter-vr` event)?

**Comment by lschatzkin** [comment]
Perhaps just making the hotspot smaller on the logo would solve the problem. Right now it's a fairly large target.
