### ISSUE TITLE
Play audio on user gesture

### ISSUE THREAD

**Issue by caseyyee** [EFForg/spot_the_surveillance#90]
as per https://github.com/EFForg/spot_the_surveillance/pull/70/files#r252493793

This is tricky since entering VR isn't necessarily required to use it.

**Comment by cvan** [comment]
> This is tricky since entering VR isn't necessarily required to use it.

could you listen on the first `click` event? (`addEventListener`, then inside the listener a `removeEventListener`.)

**Comment by cvan** [comment]
Do you want this issue to be for fixing the autoplay `NotAllowedError` JS error? And keep issue #87 for the `TypeError` arraybuffer audio bug?

**Comment by caseyyee** [comment]
Yeah, lets do that @cvan.  They are two different issues.  Thanks
