### ISSUE TITLE
Fixed ALPR/Eagle Eye overlap 

### ISSUE THREAD

**Issue by Maassive** [EFForg/spot_the_surveillance#96]
Wow, so this is Github. 

Something I noticed while testing with the HTC Vive using Nightly. 

The Excellent Work Eagle Eye card overlaps the Fixed ALPR card. So if fixed ALPR is the last of your seven, the audio is interrupted and you can't read the text.

**Comment by caseyyee** [comment]
@Maassive I think it's the same as this one?  https://github.com/EFForg/spot_the_surveillance/issues/82
If so, maybe close this issue for #82

**Comment by Maassive** [comment]
I wasn't sure whether to add it to the old one or the new one, but it's a different issue since we're talking about the Game Over card. 

BTW I'm Dave from EFF. I work with Laura on this :)

**Comment by caseyyee** [comment]
Nice alright, sounds good Dave :)
