### ISSUE TITLE
Ambient audio volume

### ISSUE THREAD

**Issue by Maassive** [EFForg/spot_the_surveillance#97]
The ambient city noise gets really loud at some points, making it difficult to make out the voiceover. If possible, we should re-record the ambient city noise so that it's more even.

**Comment by caseyyee** [comment]
Should be able to just turn down the playback volume on that click. I don't think we'll need to re-record it. Thanks for filing!

**Comment by Maassive** [comment]
There are a couple parts where a car is peeling out. I think it's just a matter of the intersection we recorded the audio. It wouldn't take a ton for me to do a longer recording closer to where the intersection actually is.

**Comment by lschatzkin** [comment]
Let's just reduce the ambient volume for now, and rerecord later.

**Comment by lschatzkin** [comment]
I feel that is used to be quieter, but don't know when that was...

**Comment by caseyyee** [comment]
OK, will make a PR for that.
